### ISSUE TITLE
Bug scan qrcode

### ISSUE THREAD

**Issue by okazakicommunity** [KurrXd/Elaine-Botz-Whatsapp#3]
[ ! ] SCAN QR NYA
√ Tersambung
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (C:\Users\Arata\Elaine-Botz-Whatsapp\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (C:\Users\Arata\Elaine-Botz-Whatsapp\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (C:\Users\Arata\Elaine-Botz-Whatsapp\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:86:18)
    at WAConnection.emit (node:events:402:35)
    at WAConnection.emit (C:\Users\Arata\Elaine-Botz-Whatsapp\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
}

C:\Users\Arata\Elaine-Botz-Whatsapp>

**Comment by KurrXd** [comment]
Cek session nya mas saya aman aman aja soalnya sama yang lain

**Comment by okazakicommunity** [comment]
session aman om

**Comment by KurrXd** [comment]
coba bikin app baru
